
// This file has been generated by the GUI designer. Do not modify.
namespace QSChat
{
	public partial class NewMessage
	{
		private global::Gtk.EventBox eventbox1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Image image123;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label labelMessageFrom;

		private global::Gtk.Button buttonClose;

		private global::Gtk.Label labelMessageText;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget QSChat.NewMessage
			this.Name = "QSChat.NewMessage";
			this.Title = global::Mono.Unix.Catalog.GetString("NewMessage");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
			this.Resizable = false;
			this.AcceptFocus = false;
			this.Decorated = false;
			this.DestroyWithParent = true;
			this.Gravity = ((global::Gdk.Gravity)(9));
			// Container child QSChat.NewMessage.Gtk.Container+ContainerChild
			this.eventbox1 = new global::Gtk.EventBox();
			this.eventbox1.Events = ((global::Gdk.EventMask)(256));
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image123 = new global::Gtk.Image();
			this.image123.Name = "image123";
			this.image123.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("QSChat.icons.mail-message-new.png");
			this.hbox2.Add(this.image123);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.image123]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(3));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labelMessageFrom = new global::Gtk.Label();
			this.labelMessageFrom.Name = "labelMessageFrom";
			this.labelMessageFrom.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
			this.hbox1.Add(this.labelMessageFrom);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.labelMessageFrom]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonClose = new global::Gtk.Button();
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseUnderline = true;
			this.buttonClose.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-close", global::Gtk.IconSize.Button);
			this.buttonClose.Image = w3;
			this.hbox1.Add(this.buttonClose);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonClose]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.labelMessageText = new global::Gtk.Label();
			this.labelMessageText.Name = "labelMessageText";
			this.labelMessageText.Xalign = 0F;
			this.labelMessageText.Yalign = 0F;
			this.labelMessageText.LabelProp = global::Mono.Unix.Catalog.GetString("label2");
			this.labelMessageText.Wrap = true;
			this.vbox1.Add(this.labelMessageText);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.labelMessageText]));
			w6.Position = 1;
			this.hbox2.Add(this.vbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox1]));
			w7.Position = 1;
			this.eventbox1.Add(this.hbox2);
			this.Add(this.eventbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 357;
			this.DefaultHeight = 72;
			this.Show();
			this.buttonClose.Clicked += new global::System.EventHandler(this.OnButtonCloseClicked);
		}
	}
}
