
// This file has been generated by the GUI designer. Do not modify.
namespace CarGlass
{
	public partial class OrderDlg
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Table table1;

		private global::QS.Widgets.GtkUI.SpecialListComboBox comboManufacturer;

		private global::QS.Widgets.GtkUI.SpecialListComboBox comboMark;

		private global::QS.Widgets.GtkUI.SpecialListComboBox comboModel;

		private global::QS.Widgets.GtkUI.SpecialListComboBox comboStatus;

		private global::QS.Widgets.GtkUI.SpecialListComboBox comboStock;

		private global::Gamma.GtkWidgets.yComboBoxEntry comboYear;

		private global::Gamma.GtkWidgets.yEntry entryEurocode;

		private global::QS.Widgets.GtkUI.PhoneEntry entryPhone;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView treeviewCost;

		private global::Gtk.Label label14;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Label label6;

		private global::Gtk.Label label8;

		private global::Gtk.Label label9;

		private global::Gtk.Label labelCreated;

		private global::Gtk.Label labelEurocode;

		private global::Gtk.Label labelGlass;

		private global::Gtk.Label labelManufacturer;

		private global::Gtk.Label labelStock;

		private global::Gtk.Label labelSum;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label7;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTextView textviewComment;

		private global::Gtk.Table table2;

		private global::Gtk.HBox hbox3;

		private global::Gamma.GtkWidgets.yRadioButton yradioInstallNone;

		private global::Gamma.GtkWidgets.yRadioButton yradioInstall1Year;

		private global::Gamma.GtkWidgets.yRadioButton yradioInstall2Year;

		private global::Gamma.GtkWidgets.yRadioButton yradioInstall3Year;

		private global::Gamma.GtkWidgets.yRadioButton yradioInstallIndefinitely;

		private global::Gamma.GtkWidgets.yRadioButton yradioInstallNoWarranty;

		private global::Gtk.HBox hbox4;

		private global::Gamma.GtkWidgets.yRadioButton yradioTintingNone;

		private global::Gamma.GtkWidgets.yRadioButton yradioTinting1Year;

		private global::Gamma.GtkWidgets.yRadioButton yradioTinting2Year;

		private global::Gamma.GtkWidgets.yRadioButton yradioTinting3Year;

		private global::Gamma.GtkWidgets.yRadioButton yradioTintingIndefinitely;

		private global::Gamma.GtkWidgets.yRadioButton yradioTintingNoWarranty;

		private global::Gtk.HBox hbox6;

		private global::Gamma.GtkWidgets.yRadioButton yradioArmoringNone;

		private global::Gamma.GtkWidgets.yRadioButton yradioArmoring1Year;

		private global::Gamma.GtkWidgets.yRadioButton yradioArmoring2Year;

		private global::Gamma.GtkWidgets.yRadioButton yradioArmoring3Year;

		private global::Gamma.GtkWidgets.yRadioButton yradioArmoringIndefinitely;

		private global::Gamma.GtkWidgets.yRadioButton yradioArmoringNoWarranty;

		private global::Gtk.HBox hbox7;

		private global::Gamma.GtkWidgets.yRadioButton yradioPastingNone;

		private global::Gamma.GtkWidgets.yRadioButton yradioPasting1Year;

		private global::Gamma.GtkWidgets.yRadioButton yradioPasting2Year;

		private global::Gamma.GtkWidgets.yRadioButton yradioPasting3Year;

		private global::Gamma.GtkWidgets.yRadioButton yradioPastingIndefinitely;

		private global::Gamma.GtkWidgets.yRadioButton yradioPastingNoWarranty;

		private global::Gtk.Label label1;

		private global::Gtk.Label label10;

		private global::Gtk.Label label11;

		private global::Gtk.Label label12;

		private global::Gtk.Label label15;

		private global::Gtk.Button buttonDelete;

		private global::Gtk.Button buttonPrint;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CarGlass.OrderDlg
			this.Name = "CarGlass.OrderDlg";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child CarGlass.OrderDlg.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(9)), ((uint)(4)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.comboManufacturer = new global::QS.Widgets.GtkUI.SpecialListComboBox();
			this.comboManufacturer.Name = "comboManufacturer";
			this.comboManufacturer.AddIfNotExist = false;
			this.comboManufacturer.DefaultFirst = false;
			this.comboManufacturer.ShowSpecialStateAll = false;
			this.comboManufacturer.ShowSpecialStateNot = false;
			this.table1.Add(this.comboManufacturer);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.comboManufacturer]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.LeftAttach = ((uint)(3));
			w2.RightAttach = ((uint)(4));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboMark = new global::QS.Widgets.GtkUI.SpecialListComboBox();
			this.comboMark.Name = "comboMark";
			this.comboMark.AddIfNotExist = false;
			this.comboMark.DefaultFirst = false;
			this.comboMark.ShowSpecialStateAll = false;
			this.comboMark.ShowSpecialStateNot = false;
			this.table1.Add(this.comboMark);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.comboMark]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboModel = new global::QS.Widgets.GtkUI.SpecialListComboBox();
			this.comboModel.Name = "comboModel";
			this.comboModel.AddIfNotExist = true;
			this.comboModel.DefaultFirst = false;
			this.comboModel.ShowSpecialStateAll = false;
			this.comboModel.ShowSpecialStateNot = false;
			this.table1.Add(this.comboModel);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.comboModel]));
			w4.TopAttach = ((uint)(3));
			w4.BottomAttach = ((uint)(4));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboStatus = new global::QS.Widgets.GtkUI.SpecialListComboBox();
			this.comboStatus.Name = "comboStatus";
			this.comboStatus.AddIfNotExist = false;
			this.comboStatus.DefaultFirst = false;
			this.comboStatus.ShowSpecialStateAll = false;
			this.comboStatus.ShowSpecialStateNot = false;
			this.table1.Add(this.comboStatus);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.comboStatus]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboStock = new global::QS.Widgets.GtkUI.SpecialListComboBox();
			this.comboStock.Name = "comboStock";
			this.comboStock.AddIfNotExist = false;
			this.comboStock.DefaultFirst = false;
			this.comboStock.ShowSpecialStateAll = false;
			this.comboStock.ShowSpecialStateNot = false;
			this.table1.Add(this.comboStock);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.comboStock]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.LeftAttach = ((uint)(3));
			w6.RightAttach = ((uint)(4));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboYear = new global::Gamma.GtkWidgets.yComboBoxEntry();
			this.comboYear.Name = "comboYear";
			this.table1.Add(this.comboYear);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.comboYear]));
			w7.TopAttach = ((uint)(4));
			w7.BottomAttach = ((uint)(5));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryEurocode = new global::Gamma.GtkWidgets.yEntry();
			this.entryEurocode.CanFocus = true;
			this.entryEurocode.Name = "entryEurocode";
			this.entryEurocode.IsEditable = true;
			this.entryEurocode.InvisibleChar = '●';
			this.table1.Add(this.entryEurocode);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.entryEurocode]));
			w8.TopAttach = ((uint)(4));
			w8.BottomAttach = ((uint)(5));
			w8.LeftAttach = ((uint)(3));
			w8.RightAttach = ((uint)(4));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryPhone = new global::QS.Widgets.GtkUI.PhoneEntry();
			this.entryPhone.CanFocus = true;
			this.entryPhone.Name = "entryPhone";
			this.entryPhone.IsEditable = true;
			this.entryPhone.InvisibleChar = '●';
			this.table1.Add(this.entryPhone);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.entryPhone]));
			w9.TopAttach = ((uint)(5));
			w9.BottomAttach = ((uint)(6));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeviewCost = new global::Gtk.TreeView();
			this.treeviewCost.CanFocus = true;
			this.treeviewCost.Name = "treeviewCost";
			this.GtkScrolledWindow1.Add(this.treeviewCost);
			this.table1.Add(this.GtkScrolledWindow1);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.GtkScrolledWindow1]));
			w11.TopAttach = ((uint)(7));
			w11.BottomAttach = ((uint)(8));
			w11.RightAttach = ((uint)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Услуги</b>");
			this.label14.UseMarkup = true;
			this.table1.Add(this.label14);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.label14]));
			w12.TopAttach = ((uint)(6));
			w12.BottomAttach = ((uint)(7));
			w12.RightAttach = ((uint)(4));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Клиент</b>");
			this.label2.UseMarkup = true;
			this.table1.Add(this.label2);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Марка<span foreground=\"red\">*</span>:");
			this.label3.UseMarkup = true;
			this.table1.Add(this.label3);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Год:");
			this.table1.Add(this.label4);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.label4]));
			w15.TopAttach = ((uint)(4));
			w15.BottomAttach = ((uint)(5));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Телефон:");
			this.table1.Add(this.label5);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.label5]));
			w16.TopAttach = ((uint)(5));
			w16.BottomAttach = ((uint)(6));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Состояние заказа<span foreground=\"red\">*</span>:");
			this.label6.UseMarkup = true;
			this.table1.Add(this.label6);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.label6]));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.Xalign = 1F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Модель<span foreground=\"red\">*</span>:");
			this.label8.UseMarkup = true;
			this.table1.Add(this.label8);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.label8]));
			w18.TopAttach = ((uint)(3));
			w18.BottomAttach = ((uint)(4));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.Xalign = 1F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Заказ создан:");
			this.table1.Add(this.label9);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.label9]));
			w19.LeftAttach = ((uint)(2));
			w19.RightAttach = ((uint)(3));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelCreated = new global::Gtk.Label();
			this.labelCreated.Name = "labelCreated";
			this.labelCreated.Xalign = 0F;
			this.labelCreated.LabelProp = global::Mono.Unix.Catalog.GetString("неизвестно");
			this.table1.Add(this.labelCreated);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1[this.labelCreated]));
			w20.LeftAttach = ((uint)(3));
			w20.RightAttach = ((uint)(4));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelEurocode = new global::Gtk.Label();
			this.labelEurocode.Name = "labelEurocode";
			this.labelEurocode.Xalign = 1F;
			this.labelEurocode.LabelProp = global::Mono.Unix.Catalog.GetString("Еврокод:");
			this.table1.Add(this.labelEurocode);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.labelEurocode]));
			w21.TopAttach = ((uint)(4));
			w21.BottomAttach = ((uint)(5));
			w21.LeftAttach = ((uint)(2));
			w21.RightAttach = ((uint)(3));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelGlass = new global::Gtk.Label();
			this.labelGlass.Name = "labelGlass";
			this.labelGlass.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Стекло</b>");
			this.labelGlass.UseMarkup = true;
			this.table1.Add(this.labelGlass);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1[this.labelGlass]));
			w22.TopAttach = ((uint)(1));
			w22.BottomAttach = ((uint)(2));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(4));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelManufacturer = new global::Gtk.Label();
			this.labelManufacturer.Name = "labelManufacturer";
			this.labelManufacturer.Xalign = 1F;
			this.labelManufacturer.LabelProp = global::Mono.Unix.Catalog.GetString("Производитель:");
			this.table1.Add(this.labelManufacturer);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1[this.labelManufacturer]));
			w23.TopAttach = ((uint)(2));
			w23.BottomAttach = ((uint)(3));
			w23.LeftAttach = ((uint)(2));
			w23.RightAttach = ((uint)(3));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelStock = new global::Gtk.Label();
			this.labelStock.Name = "labelStock";
			this.labelStock.Xalign = 1F;
			this.labelStock.LabelProp = global::Mono.Unix.Catalog.GetString("Склад:");
			this.table1.Add(this.labelStock);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1[this.labelStock]));
			w24.TopAttach = ((uint)(3));
			w24.BottomAttach = ((uint)(4));
			w24.LeftAttach = ((uint)(2));
			w24.RightAttach = ((uint)(3));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelSum = new global::Gtk.Label();
			this.labelSum.Name = "labelSum";
			this.labelSum.Xalign = 0F;
			this.labelSum.LabelProp = global::Mono.Unix.Catalog.GetString("<span foreground=\"red\"><b>Итого: 0</b></span>");
			this.labelSum.UseMarkup = true;
			this.table1.Add(this.labelSum);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1[this.labelSum]));
			w25.TopAttach = ((uint)(8));
			w25.BottomAttach = ((uint)(9));
			w25.LeftAttach = ((uint)(3));
			w25.RightAttach = ((uint)(4));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add(this.table1);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.table1]));
			w26.Position = 0;
			this.hbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w27.Position = 0;
			w1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(w1[this.hbox1]));
			w28.Position = 0;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			this.hbox2.BorderWidth = ((uint)(6));
			// Container child hbox2.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.Yalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Комментарий:");
			this.hbox2.Add(this.label7);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label7]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textviewComment = new global::Gamma.GtkWidgets.yTextView();
			this.textviewComment.CanFocus = true;
			this.textviewComment.Name = "textviewComment";
			this.GtkScrolledWindow.Add(this.textviewComment);
			this.hbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow]));
			w31.Position = 1;
			w1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(w1[this.hbox2]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table(((uint)(5)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.yradioInstallNone = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioInstallNone.CanFocus = true;
			this.yradioInstallNone.Name = "yradioInstallNone";
			this.yradioInstallNone.Label = global::Mono.Unix.Catalog.GetString("Нет");
			this.yradioInstallNone.DrawIndicator = true;
			this.yradioInstallNone.UseUnderline = true;
			this.yradioInstallNone.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.hbox3.Add(this.yradioInstallNone);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.yradioInstallNone]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.yradioInstall1Year = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioInstall1Year.CanFocus = true;
			this.yradioInstall1Year.Name = "yradioInstall1Year";
			this.yradioInstall1Year.Label = global::Mono.Unix.Catalog.GetString("1 Год");
			this.yradioInstall1Year.DrawIndicator = true;
			this.yradioInstall1Year.UseUnderline = true;
			this.yradioInstall1Year.Group = this.yradioInstallNone.Group;
			this.hbox3.Add(this.yradioInstall1Year);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.yradioInstall1Year]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.yradioInstall2Year = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioInstall2Year.CanFocus = true;
			this.yradioInstall2Year.Name = "yradioInstall2Year";
			this.yradioInstall2Year.Label = global::Mono.Unix.Catalog.GetString("2 Года");
			this.yradioInstall2Year.DrawIndicator = true;
			this.yradioInstall2Year.UseUnderline = true;
			this.yradioInstall2Year.Group = this.yradioInstallNone.Group;
			this.hbox3.Add(this.yradioInstall2Year);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.yradioInstall2Year]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.yradioInstall3Year = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioInstall3Year.CanFocus = true;
			this.yradioInstall3Year.Name = "yradioInstall3Year";
			this.yradioInstall3Year.Label = global::Mono.Unix.Catalog.GetString("3 Года");
			this.yradioInstall3Year.DrawIndicator = true;
			this.yradioInstall3Year.UseUnderline = true;
			this.yradioInstall3Year.Group = this.yradioInstallNone.Group;
			this.hbox3.Add(this.yradioInstall3Year);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.yradioInstall3Year]));
			w36.Position = 3;
			w36.Expand = false;
			w36.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.yradioInstallIndefinitely = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioInstallIndefinitely.CanFocus = true;
			this.yradioInstallIndefinitely.Name = "yradioInstallIndefinitely";
			this.yradioInstallIndefinitely.Label = global::Mono.Unix.Catalog.GetString("Бессрочно");
			this.yradioInstallIndefinitely.DrawIndicator = true;
			this.yradioInstallIndefinitely.UseUnderline = true;
			this.yradioInstallIndefinitely.Group = this.yradioInstallNone.Group;
			this.hbox3.Add(this.yradioInstallIndefinitely);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.yradioInstallIndefinitely]));
			w37.Position = 4;
			w37.Expand = false;
			w37.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.yradioInstallNoWarranty = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioInstallNoWarranty.CanFocus = true;
			this.yradioInstallNoWarranty.Name = "yradioInstallNoWarranty";
			this.yradioInstallNoWarranty.Label = global::Mono.Unix.Catalog.GetString("Без гарантии");
			this.yradioInstallNoWarranty.DrawIndicator = true;
			this.yradioInstallNoWarranty.UseUnderline = true;
			this.yradioInstallNoWarranty.Group = this.yradioInstallNone.Group;
			this.hbox3.Add(this.yradioInstallNoWarranty);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.yradioInstallNoWarranty]));
			w38.Position = 5;
			w38.Expand = false;
			w38.Fill = false;
			this.table2.Add(this.hbox3);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table2[this.hbox3]));
			w39.TopAttach = ((uint)(1));
			w39.BottomAttach = ((uint)(2));
			w39.LeftAttach = ((uint)(1));
			w39.RightAttach = ((uint)(2));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.yradioTintingNone = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioTintingNone.CanFocus = true;
			this.yradioTintingNone.Name = "yradioTintingNone";
			this.yradioTintingNone.Label = global::Mono.Unix.Catalog.GetString("Нет");
			this.yradioTintingNone.DrawIndicator = true;
			this.yradioTintingNone.UseUnderline = true;
			this.yradioTintingNone.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.hbox4.Add(this.yradioTintingNone);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.yradioTintingNone]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.yradioTinting1Year = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioTinting1Year.CanFocus = true;
			this.yradioTinting1Year.Name = "yradioTinting1Year";
			this.yradioTinting1Year.Label = global::Mono.Unix.Catalog.GetString("1 Год");
			this.yradioTinting1Year.DrawIndicator = true;
			this.yradioTinting1Year.UseUnderline = true;
			this.yradioTinting1Year.Group = this.yradioTintingNone.Group;
			this.hbox4.Add(this.yradioTinting1Year);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.yradioTinting1Year]));
			w41.Position = 1;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.yradioTinting2Year = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioTinting2Year.CanFocus = true;
			this.yradioTinting2Year.Name = "yradioTinting2Year";
			this.yradioTinting2Year.Label = global::Mono.Unix.Catalog.GetString("2 Года");
			this.yradioTinting2Year.DrawIndicator = true;
			this.yradioTinting2Year.UseUnderline = true;
			this.yradioTinting2Year.Group = this.yradioTintingNone.Group;
			this.hbox4.Add(this.yradioTinting2Year);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.yradioTinting2Year]));
			w42.Position = 2;
			w42.Expand = false;
			w42.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.yradioTinting3Year = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioTinting3Year.CanFocus = true;
			this.yradioTinting3Year.Name = "yradioTinting3Year";
			this.yradioTinting3Year.Label = global::Mono.Unix.Catalog.GetString("3 Года");
			this.yradioTinting3Year.DrawIndicator = true;
			this.yradioTinting3Year.UseUnderline = true;
			this.yradioTinting3Year.Group = this.yradioTintingNone.Group;
			this.hbox4.Add(this.yradioTinting3Year);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.yradioTinting3Year]));
			w43.Position = 3;
			w43.Expand = false;
			w43.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.yradioTintingIndefinitely = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioTintingIndefinitely.CanFocus = true;
			this.yradioTintingIndefinitely.Name = "yradioTintingIndefinitely";
			this.yradioTintingIndefinitely.Label = global::Mono.Unix.Catalog.GetString("Бессрочно");
			this.yradioTintingIndefinitely.DrawIndicator = true;
			this.yradioTintingIndefinitely.UseUnderline = true;
			this.yradioTintingIndefinitely.Group = this.yradioTintingNone.Group;
			this.hbox4.Add(this.yradioTintingIndefinitely);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.yradioTintingIndefinitely]));
			w44.Position = 4;
			w44.Expand = false;
			w44.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.yradioTintingNoWarranty = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioTintingNoWarranty.CanFocus = true;
			this.yradioTintingNoWarranty.Name = "yradioTintingNoWarranty";
			this.yradioTintingNoWarranty.Label = global::Mono.Unix.Catalog.GetString("Без гарантии");
			this.yradioTintingNoWarranty.DrawIndicator = true;
			this.yradioTintingNoWarranty.UseUnderline = true;
			this.yradioTintingNoWarranty.Group = this.yradioTintingNone.Group;
			this.hbox4.Add(this.yradioTintingNoWarranty);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.yradioTintingNoWarranty]));
			w45.Position = 5;
			w45.Expand = false;
			w45.Fill = false;
			this.table2.Add(this.hbox4);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table2[this.hbox4]));
			w46.TopAttach = ((uint)(2));
			w46.BottomAttach = ((uint)(3));
			w46.LeftAttach = ((uint)(1));
			w46.RightAttach = ((uint)(2));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.yradioArmoringNone = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioArmoringNone.CanFocus = true;
			this.yradioArmoringNone.Name = "yradioArmoringNone";
			this.yradioArmoringNone.Label = global::Mono.Unix.Catalog.GetString("Нет");
			this.yradioArmoringNone.DrawIndicator = true;
			this.yradioArmoringNone.UseUnderline = true;
			this.yradioArmoringNone.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.hbox6.Add(this.yradioArmoringNone);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.yradioArmoringNone]));
			w47.Position = 0;
			w47.Expand = false;
			w47.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.yradioArmoring1Year = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioArmoring1Year.CanFocus = true;
			this.yradioArmoring1Year.Name = "yradioArmoring1Year";
			this.yradioArmoring1Year.Label = global::Mono.Unix.Catalog.GetString("1 Год");
			this.yradioArmoring1Year.DrawIndicator = true;
			this.yradioArmoring1Year.UseUnderline = true;
			this.yradioArmoring1Year.Group = this.yradioArmoringNone.Group;
			this.hbox6.Add(this.yradioArmoring1Year);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.yradioArmoring1Year]));
			w48.Position = 1;
			w48.Expand = false;
			w48.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.yradioArmoring2Year = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioArmoring2Year.CanFocus = true;
			this.yradioArmoring2Year.Name = "yradioArmoring2Year";
			this.yradioArmoring2Year.Label = global::Mono.Unix.Catalog.GetString("2 Года");
			this.yradioArmoring2Year.DrawIndicator = true;
			this.yradioArmoring2Year.UseUnderline = true;
			this.yradioArmoring2Year.Group = this.yradioArmoringNone.Group;
			this.hbox6.Add(this.yradioArmoring2Year);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.yradioArmoring2Year]));
			w49.Position = 2;
			w49.Expand = false;
			w49.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.yradioArmoring3Year = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioArmoring3Year.CanFocus = true;
			this.yradioArmoring3Year.Name = "yradioArmoring3Year";
			this.yradioArmoring3Year.Label = global::Mono.Unix.Catalog.GetString("3 Года");
			this.yradioArmoring3Year.DrawIndicator = true;
			this.yradioArmoring3Year.UseUnderline = true;
			this.yradioArmoring3Year.Group = this.yradioArmoringNone.Group;
			this.hbox6.Add(this.yradioArmoring3Year);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.yradioArmoring3Year]));
			w50.Position = 3;
			w50.Expand = false;
			w50.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.yradioArmoringIndefinitely = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioArmoringIndefinitely.CanFocus = true;
			this.yradioArmoringIndefinitely.Name = "yradioArmoringIndefinitely";
			this.yradioArmoringIndefinitely.Label = global::Mono.Unix.Catalog.GetString("Бессрочно");
			this.yradioArmoringIndefinitely.DrawIndicator = true;
			this.yradioArmoringIndefinitely.UseUnderline = true;
			this.yradioArmoringIndefinitely.Group = this.yradioArmoringNone.Group;
			this.hbox6.Add(this.yradioArmoringIndefinitely);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.yradioArmoringIndefinitely]));
			w51.Position = 4;
			w51.Expand = false;
			w51.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.yradioArmoringNoWarranty = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioArmoringNoWarranty.CanFocus = true;
			this.yradioArmoringNoWarranty.Name = "yradioArmoringNoWarranty";
			this.yradioArmoringNoWarranty.Label = global::Mono.Unix.Catalog.GetString("Без гарантии");
			this.yradioArmoringNoWarranty.DrawIndicator = true;
			this.yradioArmoringNoWarranty.UseUnderline = true;
			this.yradioArmoringNoWarranty.Group = this.yradioArmoringNone.Group;
			this.hbox6.Add(this.yradioArmoringNoWarranty);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.yradioArmoringNoWarranty]));
			w52.Position = 5;
			w52.Expand = false;
			w52.Fill = false;
			this.table2.Add(this.hbox6);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table2[this.hbox6]));
			w53.TopAttach = ((uint)(3));
			w53.BottomAttach = ((uint)(4));
			w53.LeftAttach = ((uint)(1));
			w53.RightAttach = ((uint)(2));
			w53.XOptions = ((global::Gtk.AttachOptions)(4));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.yradioPastingNone = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioPastingNone.CanFocus = true;
			this.yradioPastingNone.Name = "yradioPastingNone";
			this.yradioPastingNone.Label = global::Mono.Unix.Catalog.GetString("Нет");
			this.yradioPastingNone.DrawIndicator = true;
			this.yradioPastingNone.UseUnderline = true;
			this.yradioPastingNone.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.hbox7.Add(this.yradioPastingNone);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.yradioPastingNone]));
			w54.Position = 0;
			w54.Expand = false;
			w54.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.yradioPasting1Year = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioPasting1Year.CanFocus = true;
			this.yradioPasting1Year.Name = "yradioPasting1Year";
			this.yradioPasting1Year.Label = global::Mono.Unix.Catalog.GetString("1 Год");
			this.yradioPasting1Year.DrawIndicator = true;
			this.yradioPasting1Year.UseUnderline = true;
			this.yradioPasting1Year.Group = this.yradioPastingNone.Group;
			this.hbox7.Add(this.yradioPasting1Year);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.yradioPasting1Year]));
			w55.Position = 1;
			w55.Expand = false;
			w55.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.yradioPasting2Year = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioPasting2Year.CanFocus = true;
			this.yradioPasting2Year.Name = "yradioPasting2Year";
			this.yradioPasting2Year.Label = global::Mono.Unix.Catalog.GetString("2 Года");
			this.yradioPasting2Year.DrawIndicator = true;
			this.yradioPasting2Year.UseUnderline = true;
			this.yradioPasting2Year.Group = this.yradioPastingNone.Group;
			this.hbox7.Add(this.yradioPasting2Year);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.yradioPasting2Year]));
			w56.Position = 2;
			w56.Expand = false;
			w56.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.yradioPasting3Year = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioPasting3Year.CanFocus = true;
			this.yradioPasting3Year.Name = "yradioPasting3Year";
			this.yradioPasting3Year.Label = global::Mono.Unix.Catalog.GetString("3 Года");
			this.yradioPasting3Year.DrawIndicator = true;
			this.yradioPasting3Year.UseUnderline = true;
			this.yradioPasting3Year.Group = this.yradioPastingNone.Group;
			this.hbox7.Add(this.yradioPasting3Year);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.yradioPasting3Year]));
			w57.Position = 3;
			w57.Expand = false;
			w57.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.yradioPastingIndefinitely = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioPastingIndefinitely.CanFocus = true;
			this.yradioPastingIndefinitely.Name = "yradioPastingIndefinitely";
			this.yradioPastingIndefinitely.Label = global::Mono.Unix.Catalog.GetString("Бессрочно");
			this.yradioPastingIndefinitely.DrawIndicator = true;
			this.yradioPastingIndefinitely.UseUnderline = true;
			this.yradioPastingIndefinitely.Group = this.yradioPastingNone.Group;
			this.hbox7.Add(this.yradioPastingIndefinitely);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.yradioPastingIndefinitely]));
			w58.Position = 4;
			w58.Expand = false;
			w58.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.yradioPastingNoWarranty = new global::Gamma.GtkWidgets.yRadioButton();
			this.yradioPastingNoWarranty.CanFocus = true;
			this.yradioPastingNoWarranty.Name = "yradioPastingNoWarranty";
			this.yradioPastingNoWarranty.Label = global::Mono.Unix.Catalog.GetString("Без гарантии");
			this.yradioPastingNoWarranty.DrawIndicator = true;
			this.yradioPastingNoWarranty.UseUnderline = true;
			this.yradioPastingNoWarranty.Group = this.yradioPastingNone.Group;
			this.hbox7.Add(this.yradioPastingNoWarranty);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.yradioPastingNoWarranty]));
			w59.Position = 5;
			w59.Expand = false;
			w59.Fill = false;
			this.table2.Add(this.hbox7);
			global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.table2[this.hbox7]));
			w60.TopAttach = ((uint)(4));
			w60.BottomAttach = ((uint)(5));
			w60.LeftAttach = ((uint)(1));
			w60.RightAttach = ((uint)(2));
			w60.XOptions = ((global::Gtk.AttachOptions)(4));
			w60.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Гарантия</b>");
			this.label1.UseMarkup = true;
			this.table2.Add(this.label1);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table2[this.label1]));
			w61.RightAttach = ((uint)(2));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.Xalign = 1F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Установка:");
			this.table2.Add(this.label10);
			global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table2[this.label10]));
			w62.TopAttach = ((uint)(1));
			w62.BottomAttach = ((uint)(2));
			w62.XOptions = ((global::Gtk.AttachOptions)(4));
			w62.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.Xalign = 1F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Тонировка:");
			this.table2.Add(this.label11);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.table2[this.label11]));
			w63.TopAttach = ((uint)(2));
			w63.BottomAttach = ((uint)(3));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.Xalign = 1F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Бронировка:");
			this.table2.Add(this.label12);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table2[this.label12]));
			w64.TopAttach = ((uint)(3));
			w64.BottomAttach = ((uint)(4));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.Xalign = 1F;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Оклейка:");
			this.table2.Add(this.label15);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table2[this.label15]));
			w65.TopAttach = ((uint)(4));
			w65.BottomAttach = ((uint)(5));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add(this.table2);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(w1[this.table2]));
			w66.Position = 2;
			w66.Expand = false;
			// Internal child CarGlass.OrderDlg.ActionArea
			global::Gtk.HButtonBox w67 = this.ActionArea;
			w67.Name = "dialog1_ActionArea";
			w67.Spacing = 10;
			w67.BorderWidth = ((uint)(5));
			w67.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonDelete = new global::Gtk.Button();
			this.buttonDelete.Sensitive = false;
			this.buttonDelete.CanFocus = true;
			this.buttonDelete.Name = "buttonDelete";
			this.buttonDelete.UseStock = true;
			this.buttonDelete.UseUnderline = true;
			this.buttonDelete.Label = "gtk-delete";
			w67.Add(this.buttonDelete);
			global::Gtk.ButtonBox.ButtonBoxChild w68 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w67[this.buttonDelete]));
			w68.Expand = false;
			w68.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonPrint = new global::Gtk.Button();
			this.buttonPrint.Sensitive = false;
			this.buttonPrint.CanFocus = true;
			this.buttonPrint.Name = "buttonPrint";
			this.buttonPrint.UseStock = true;
			this.buttonPrint.UseUnderline = true;
			this.buttonPrint.Label = "gtk-print";
			w67.Add(this.buttonPrint);
			global::Gtk.ButtonBox.ButtonBoxChild w69 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w67[this.buttonPrint]));
			w69.Position = 1;
			w69.Expand = false;
			w69.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w70 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w67[this.buttonCancel]));
			w70.Position = 2;
			w70.Expand = false;
			w70.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.Sensitive = false;
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			w67.Add(this.buttonOk);
			global::Gtk.ButtonBox.ButtonBoxChild w71 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w67[this.buttonOk]));
			w71.Position = 3;
			w71.Expand = false;
			w71.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 628;
			this.DefaultHeight = 670;
			this.Show();
			this.comboStatus.Changed += new global::System.EventHandler(this.OnComboStatusChanged);
			this.comboModel.Changed += new global::System.EventHandler(this.OnComboModelChanged);
			this.comboMark.Changed += new global::System.EventHandler(this.OnComboMarkChanged);
			this.buttonDelete.Clicked += new global::System.EventHandler(this.OnButtonDeleteClicked);
			this.buttonPrint.Clicked += new global::System.EventHandler(this.OnButtonPrintClicked);
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
