
// This file has been generated by the GUI designer. Do not modify.
namespace CarGlass.Dialogs
{
	public partial class EmployeesKoef
	{
		private global::Gtk.VBox vbox5;

		private global::Gtk.Table table1;

		private global::QS.Widgets.GtkUI.SpecialListComboBox comboCoeff;

		private global::QS.Widgets.GtkUI.SpecialListComboBox comboEmployees;

		private global::Gtk.Label label12;

		private global::Gtk.Label label13;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTreeView ytree;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button btnSave;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CarGlass.Dialogs.EmployeesKoef
			global::Stetic.BinContainer.Attach(this);
			this.Name = "CarGlass.Dialogs.EmployeesKoef";
			// Container child CarGlass.Dialogs.EmployeesKoef.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(1)), ((uint)(4)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.comboCoeff = new global::QS.Widgets.GtkUI.SpecialListComboBox();
			this.comboCoeff.Name = "comboCoeff";
			this.comboCoeff.AddIfNotExist = false;
			this.comboCoeff.DefaultFirst = false;
			this.comboCoeff.ShowSpecialStateAll = false;
			this.comboCoeff.ShowSpecialStateNot = false;
			this.table1.Add(this.comboCoeff);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.comboCoeff]));
			w1.LeftAttach = ((uint)(3));
			w1.RightAttach = ((uint)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboEmployees = new global::QS.Widgets.GtkUI.SpecialListComboBox();
			this.comboEmployees.Name = "comboEmployees";
			this.comboEmployees.AddIfNotExist = false;
			this.comboEmployees.DefaultFirst = false;
			this.comboEmployees.ShowSpecialStateAll = false;
			this.comboEmployees.ShowSpecialStateNot = false;
			this.table1.Add(this.comboEmployees);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.comboEmployees]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Сотрудник:");
			this.table1.Add(this.label12);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.label12]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Коеф.");
			this.table1.Add(this.label13);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.label13]));
			w4.LeftAttach = ((uint)(2));
			w4.RightAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox5.Add(this.table1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.table1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytree = new global::Gamma.GtkWidgets.yTreeView();
			this.ytree.CanFocus = true;
			this.ytree.Name = "ytree";
			this.GtkScrolledWindow.Add(this.ytree);
			this.vbox5.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.GtkScrolledWindow]));
			w7.Position = 1;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnSave = new global::Gtk.Button();
			this.btnSave.CanFocus = true;
			this.btnSave.Name = "btnSave";
			this.btnSave.UseUnderline = true;
			this.btnSave.Label = global::Mono.Unix.Catalog.GetString("Сохранить");
			this.hbox1.Add(this.btnSave);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnSave]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox5.Add(this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox1]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.Add(this.vbox5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.ytree.Hide();
			this.Hide();
			this.comboEmployees.ItemSelected += new global::System.EventHandler<Gamma.Widgets.ItemSelectedEventArgs>(this.OnComboMarkItemSelected);
			this.comboCoeff.ItemSelected += new global::System.EventHandler<Gamma.Widgets.ItemSelectedEventArgs>(this.OnComboMark1ItemSelected);
			this.btnSave.Clicked += new global::System.EventHandler(this.OnBtnSaveClicked);
		}
	}
}
