
// This file has been generated by the GUI designer. Do not modify.
namespace CarGlass.Dialogs
{
	public partial class EmployeesCatalog
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label10;

		private global::Gamma.GtkWidgets.yCheckButton ycheckbutton1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTreeView ytree;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Button btnAdd;

		private global::Gtk.Button btnAccept;

		private global::Gtk.Button btnDismiss;

		private global::Gtk.Button btnSave;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CarGlass.Dialogs.EmployeesCatalog
			global::Stetic.BinContainer.Attach(this);
			this.Name = "CarGlass.Dialogs.EmployeesCatalog";
			// Container child CarGlass.Dialogs.EmployeesCatalog.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Сотрудники:");
			this.hbox6.Add(this.label10);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label10]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.ycheckbutton1 = new global::Gamma.GtkWidgets.yCheckButton();
			this.ycheckbutton1.CanFocus = true;
			this.ycheckbutton1.Name = "ycheckbutton1";
			this.ycheckbutton1.Label = global::Mono.Unix.Catalog.GetString("работающие");
			this.ycheckbutton1.Active = true;
			this.ycheckbutton1.DrawIndicator = true;
			this.ycheckbutton1.UseUnderline = true;
			this.hbox6.Add(this.ycheckbutton1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.ycheckbutton1]));
			w2.Position = 3;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox4.Add(this.hbox6);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox6]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytree = new global::Gamma.GtkWidgets.yTreeView();
			this.ytree.CanFocus = true;
			this.ytree.Name = "ytree";
			this.GtkScrolledWindow.Add(this.ytree);
			this.vbox4.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow]));
			w5.Position = 1;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.btnAdd = new global::Gtk.Button();
			this.btnAdd.CanFocus = true;
			this.btnAdd.Name = "btnAdd";
			this.btnAdd.UseUnderline = true;
			this.btnAdd.Label = global::Mono.Unix.Catalog.GetString("Добавить");
			this.hbox7.Add(this.btnAdd);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.btnAdd]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.btnAccept = new global::Gtk.Button();
			this.btnAccept.Sensitive = false;
			this.btnAccept.CanFocus = true;
			this.btnAccept.Name = "btnAccept";
			this.btnAccept.UseUnderline = true;
			this.btnAccept.Label = global::Mono.Unix.Catalog.GetString("Принять");
			this.hbox7.Add(this.btnAccept);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.btnAccept]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.btnDismiss = new global::Gtk.Button();
			this.btnDismiss.CanFocus = true;
			this.btnDismiss.Name = "btnDismiss";
			this.btnDismiss.UseUnderline = true;
			this.btnDismiss.Label = global::Mono.Unix.Catalog.GetString("Уволить");
			this.hbox7.Add(this.btnDismiss);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.btnDismiss]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.btnSave = new global::Gtk.Button();
			this.btnSave.CanFocus = true;
			this.btnSave.Name = "btnSave";
			this.btnSave.UseUnderline = true;
			this.btnSave.Label = global::Mono.Unix.Catalog.GetString("Сохранить");
			this.hbox7.Add(this.btnSave);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.btnSave]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox4.Add(this.hbox7);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox7]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.ytree.Hide();
			this.Hide();
			this.ycheckbutton1.Clicked += new global::System.EventHandler(this.OnYcheckbutton1Clicked);
			this.btnAdd.Clicked += new global::System.EventHandler(this.OnBtnAddClicked);
			this.btnAccept.Clicked += new global::System.EventHandler(this.OnBtnAcceptClicked);
			this.btnDismiss.Clicked += new global::System.EventHandler(this.OnBtnDismissClicked);
			this.btnSave.Clicked += new global::System.EventHandler(this.OnBtnSaveClicked);
		}
	}
}
