
// This file has been generated by the GUI designer. Do not modify.
namespace CarGlass.Dialogs
{
	public partial class SalaryCalculation
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label2;

		private global::QS.Widgets.GtkUI.DateRangePicker daterangepicker1;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.Button btnCalc;

		private global::Gtk.Button btnSetting;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label5;

		private global::QS.Widgets.GtkUI.SpecialListComboBox cmbEmployees;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gamma.GtkWidgets.yTreeView ytreeMain;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label6;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView treeviewCost1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CarGlass.Dialogs.SalaryCalculation
			global::Stetic.BinContainer.Attach(this);
			this.Name = "CarGlass.Dialogs.SalaryCalculation";
			// Container child CarGlass.Dialogs.SalaryCalculation.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Период расчета:");
			this.hbox1.Add(this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.daterangepicker1 = new global::QS.Widgets.GtkUI.DateRangePicker();
			this.daterangepicker1.Events = ((global::Gdk.EventMask)(256));
			this.daterangepicker1.Name = "daterangepicker1";
			this.daterangepicker1.StartDate = new global::System.DateTime(0);
			this.daterangepicker1.EndDate = new global::System.DateTime(0);
			this.hbox1.Add(this.daterangepicker1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.daterangepicker1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.hbox1.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hseparator1]));
			w3.Position = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnCalc = new global::Gtk.Button();
			this.btnCalc.CanFocus = true;
			this.btnCalc.Name = "btnCalc";
			this.btnCalc.UseUnderline = true;
			this.btnCalc.Label = global::Mono.Unix.Catalog.GetString("Рассчитать");
			this.hbox1.Add(this.btnCalc);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnCalc]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnSetting = new global::Gtk.Button();
			this.btnSetting.CanFocus = true;
			this.btnSetting.Name = "btnSetting";
			this.btnSetting.UseUnderline = true;
			this.btnSetting.Label = global::Mono.Unix.Catalog.GetString("Настройки");
			this.hbox1.Add(this.btnSetting);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnSetting]));
			w5.Position = 5;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Сотрудники:");
			this.hbox4.Add(this.label5);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label5]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.cmbEmployees = new global::QS.Widgets.GtkUI.SpecialListComboBox();
			this.cmbEmployees.Name = "cmbEmployees";
			this.cmbEmployees.AddIfNotExist = false;
			this.cmbEmployees.DefaultFirst = false;
			this.cmbEmployees.ShowSpecialStateAll = false;
			this.cmbEmployees.ShowSpecialStateNot = false;
			this.hbox4.Add(this.cmbEmployees);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.cmbEmployees]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox2.Add(this.hbox4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ytreeMain = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeMain.CanFocus = true;
			this.ytreeMain.Name = "ytreeMain";
			this.GtkScrolledWindow.Add(this.ytreeMain);
			this.vbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
			w11.Position = 2;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Список работ:");
			this.hbox5.Add(this.label6);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label6]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox2.Add(this.hbox5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeviewCost1 = new global::Gtk.TreeView();
			this.treeviewCost1.CanFocus = true;
			this.treeviewCost1.Name = "treeviewCost1";
			this.GtkScrolledWindow1.Add(this.treeviewCost1);
			this.vbox2.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow1]));
			w15.Position = 4;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.ytreeMain.Hide();
			this.Hide();
			this.btnCalc.Clicked += new global::System.EventHandler(this.OnBtnCalcClicked);
			this.btnSetting.Clicked += new global::System.EventHandler(this.OnBtnSettingClicked);
		}
	}
}
