
// This file has been generated by the GUI designer. Do not modify.
namespace CarGlass.Dialogs
{
	public partial class StockBalance
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::CarGlass.Widgets.GlassSelector glassselector;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox3;

		private global::Gamma.GtkWidgets.yEntry yentrySearch;

		private global::Gtk.Button buttonSearchClean;

		private global::Gamma.GtkWidgets.yLabel ylabel1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::QSOrmProject.RepresentationTreeView representationViewStoreItems;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button buttonAddRow;

		private global::Gtk.Button buttonEdit;

		private global::Gtk.Button buttonDeleteRow;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CarGlass.Dialogs.StockBalance
			global::Stetic.BinContainer.Attach(this);
			this.Name = "CarGlass.Dialogs.StockBalance";
			// Container child CarGlass.Dialogs.StockBalance.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.glassselector = new global::CarGlass.Widgets.GlassSelector();
			this.glassselector.WidthRequest = 300;
			this.glassselector.HeightRequest = 250;
			this.glassselector.Name = "glassselector";
			this.hbox1.Add(this.glassselector);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.glassselector]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.yentrySearch = new global::Gamma.GtkWidgets.yEntry();
			this.yentrySearch.CanFocus = true;
			this.yentrySearch.Name = "yentrySearch";
			this.yentrySearch.IsEditable = true;
			this.yentrySearch.InvisibleChar = '●';
			this.hbox3.Add(this.yentrySearch);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.yentrySearch]));
			w2.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonSearchClean = new global::Gtk.Button();
			this.buttonSearchClean.CanFocus = true;
			this.buttonSearchClean.Name = "buttonSearchClean";
			this.buttonSearchClean.UseUnderline = true;
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-clear", global::Gtk.IconSize.Menu);
			this.buttonSearchClean.Image = w3;
			this.hbox3.Add(this.buttonSearchClean);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.buttonSearchClean]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.ylabel1 = new global::Gamma.GtkWidgets.yLabel();
			this.ylabel1.Name = "ylabel1";
			this.ylabel1.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Поиск:</b>");
			this.ylabel1.UseMarkup = true;
			this.vbox1.Add(this.ylabel1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.ylabel1]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.hbox1.Add(this.vbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
			w7.Position = 1;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.representationViewStoreItems = new global::QSOrmProject.RepresentationTreeView();
			this.representationViewStoreItems.CanFocus = true;
			this.representationViewStoreItems.Name = "representationViewStoreItems";
			this.GtkScrolledWindow.Add(this.representationViewStoreItems);
			this.vbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
			w10.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonAddRow = new global::Gtk.Button();
			this.buttonAddRow.CanFocus = true;
			this.buttonAddRow.Name = "buttonAddRow";
			this.buttonAddRow.UseUnderline = true;
			this.buttonAddRow.Label = global::Mono.Unix.Catalog.GetString("Добавить");
			global::Gtk.Image w11 = new global::Gtk.Image();
			w11.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Menu);
			this.buttonAddRow.Image = w11;
			this.hbox2.Add(this.buttonAddRow);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.buttonAddRow]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonEdit = new global::Gtk.Button();
			this.buttonEdit.CanFocus = true;
			this.buttonEdit.Name = "buttonEdit";
			this.buttonEdit.UseUnderline = true;
			this.buttonEdit.Label = global::Mono.Unix.Catalog.GetString("Изменить");
			global::Gtk.Image w13 = new global::Gtk.Image();
			w13.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.buttonEdit.Image = w13;
			this.hbox2.Add(this.buttonEdit);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.buttonEdit]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonDeleteRow = new global::Gtk.Button();
			this.buttonDeleteRow.Sensitive = false;
			this.buttonDeleteRow.CanFocus = true;
			this.buttonDeleteRow.Name = "buttonDeleteRow";
			this.buttonDeleteRow.UseUnderline = true;
			this.buttonDeleteRow.Label = global::Mono.Unix.Catalog.GetString("Удалить");
			global::Gtk.Image w15 = new global::Gtk.Image();
			w15.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-remove", global::Gtk.IconSize.Menu);
			this.buttonDeleteRow.Image = w15;
			this.hbox2.Add(this.buttonDeleteRow);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.buttonDeleteRow]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox2.Add(this.hbox2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.glassselector.GlassChanged += new global::System.EventHandler(this.OnGlassselectorGlassChanged);
			this.yentrySearch.Changed += new global::System.EventHandler(this.OnYentrySearchChanged);
			this.buttonSearchClean.Clicked += new global::System.EventHandler(this.OnButtonSearchCleanClicked);
			this.representationViewStoreItems.RowActivated += new global::Gtk.RowActivatedHandler(this.OnRepresentationViewStoreItemsRowActivated);
			this.buttonAddRow.Clicked += new global::System.EventHandler(this.OnButtonAddRowClicked);
			this.buttonEdit.Clicked += new global::System.EventHandler(this.OnButtonEditClicked);
			this.buttonDeleteRow.Clicked += new global::System.EventHandler(this.OnButtonDeleteRowClicked);
		}
	}
}
