
// This file has been generated by the GUI designer. Do not modify.
namespace CarGlass
{
	public partial class GlassOrders
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.Table table1;

		private global::QSWidgetLib.CheckList checklistStock;

		private global::Gtk.ComboBox comboStatus;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::QSWidgetLib.SelectPeriod selectperiod1;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CarGlass.GlassOrders
			this.Name = "CarGlass.GlassOrders";
			this.Title = global::Mono.Unix.Catalog.GetString("Отчет по заказам");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child CarGlass.GlassOrders.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			this.hbox1.BorderWidth = ((uint)(6));
			// Container child hbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.checklistStock = new global::QSWidgetLib.CheckList();
			this.checklistStock.Name = "checklistStock";
			this.table1.Add(this.checklistStock);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.checklistStock]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboStatus = global::Gtk.ComboBox.NewText();
			this.comboStatus.Name = "comboStatus";
			this.table1.Add(this.comboStatus);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.comboStatus]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Статус заказа:");
			this.table1.Add(this.label3);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Склады:");
			this.table1.Add(this.label4);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.label4]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox1.Add(this.table1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.table1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.selectperiod1 = new global::QSWidgetLib.SelectPeriod();
			this.selectperiod1.Events = ((global::Gdk.EventMask)(256));
			this.selectperiod1.Name = "selectperiod1";
			this.selectperiod1.DateBegin = new global::System.DateTime(0);
			this.selectperiod1.DateEnd = new global::System.DateTime(0);
			this.selectperiod1.AutoDateSeparation = true;
			this.selectperiod1.ShowToday = true;
			this.selectperiod1.ShowWeek = false;
			this.selectperiod1.ShowMonth = false;
			this.selectperiod1.Show3Month = false;
			this.selectperiod1.Show6Month = false;
			this.selectperiod1.ShowYear = false;
			this.selectperiod1.ShowAllTime = false;
			this.selectperiod1.ShowCurWeek = true;
			this.selectperiod1.ShowCurMonth = true;
			this.selectperiod1.ShowCurQuarter = false;
			this.selectperiod1.ShowCurYear = true;
			this.selectperiod1.ShowCustomPeriod = false;
			this.selectperiod1.WithTime = false;
			this.hbox1.Add(this.selectperiod1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.selectperiod1]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			w1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1[this.hbox1]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Internal child CarGlass.GlassOrders.ActionArea
			global::Gtk.HButtonBox w9 = this.ActionArea;
			w9.Name = "dialog1_ActionArea";
			w9.Spacing = 10;
			w9.BorderWidth = ((uint)(5));
			w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9[this.buttonCancel]));
			w10.Expand = false;
			w10.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.Sensitive = false;
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9[this.buttonOk]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 486;
			this.DefaultHeight = 248;
			this.Show();
			this.comboStatus.Changed += new global::System.EventHandler(this.OnComboStatusChanged);
			this.checklistStock.CheckListClicked += new global::System.EventHandler<QSWidgetLib.CheckListClickedEventArgs>(this.OnChecklistStockCheckListClicked);
			this.selectperiod1.DatesChanged += new global::System.EventHandler(this.OnSelectperiod1DatesChanged);
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
