
// This file has been generated by the GUI designer. Do not modify.
namespace CarGlass.Views.SMS
{
	public partial class MessageHistoryView
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CarGlass.Views.SMS.MessageHistoryView
			global::Stetic.BinContainer.Attach(this);
			this.Name = "CarGlass.Views.SMS.MessageHistoryView";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
