
// This file has been generated by the GUI designer. Do not modify.
namespace CarGlass.Dialogs
{
	public partial class SalaryFormulas
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label8;

		private global::Gtk.ScrolledWindow GtkScrolledWindow2;

		private global::Gamma.GtkWidgets.yTreeView ytreeFormulas;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button btnEditFormula;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CarGlass.Dialogs.SalaryFormulas
			global::Stetic.BinContainer.Attach(this);
			this.Name = "CarGlass.Dialogs.SalaryFormulas";
			// Container child CarGlass.Dialogs.SalaryFormulas.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Формулы расчета:");
			this.hbox4.Add(this.label8);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label8]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.vbox3.Add(this.hbox4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.ytreeFormulas = new global::Gamma.GtkWidgets.yTreeView();
			this.ytreeFormulas.CanFocus = true;
			this.ytreeFormulas.Name = "ytreeFormulas";
			this.GtkScrolledWindow2.Add(this.ytreeFormulas);
			this.vbox3.Add(this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow2]));
			w4.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnEditFormula = new global::Gtk.Button();
			this.btnEditFormula.Sensitive = false;
			this.btnEditFormula.CanFocus = true;
			this.btnEditFormula.Name = "btnEditFormula";
			this.btnEditFormula.UseUnderline = true;
			this.btnEditFormula.Label = global::Mono.Unix.Catalog.GetString("Редактировать");
			this.hbox1.Add(this.btnEditFormula);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnEditFormula]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox3.Add(this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.Add(this.vbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.btnEditFormula.Clicked += new global::System.EventHandler(this.OnBtnEditFormulaClicked);
		}
	}
}
