
// This file has been generated by the GUI designer. Do not modify.
namespace CarGlass.Dialogs
{
	public partial class ClientCalendar
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.EventBox eventbox;

		private global::Gtk.Table tableOrders;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CarGlass.Dialogs.ClientCalendar
			this.Name = "CarGlass.Dialogs.ClientCalendar";
			this.Title = global::Mono.Unix.Catalog.GetString("ClientCalendar");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child CarGlass.Dialogs.ClientCalendar.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.eventbox = new global::Gtk.EventBox();
			this.eventbox.Name = "eventbox";
			// Container child eventbox.Gtk.Container+ContainerChild
			this.tableOrders = new global::Gtk.Table(((uint)(3)), ((uint)(8)), false);
			this.tableOrders.Name = "tableOrders";
			this.tableOrders.RowSpacing = ((uint)(1));
			this.tableOrders.ColumnSpacing = ((uint)(1));
			this.eventbox.Add(this.tableOrders);
			this.hbox1.Add(this.eventbox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.eventbox]));
			w2.Position = 0;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.tableOrders.ExposeEvent += new global::Gtk.ExposeEventHandler(this.OnTableOrdersExposeEvent);
		}
	}
}
